services:

  frontend:
    image: ${FRONTEND_IMAGE}:${FRONTEND_TAG}
    environment:
      CATALOG: $FRONTEND_CATALOG
      ORDERS: $FRONTEND_ORDERS
      PAYMENT: $FRONTEND_PAYMENT
    restart: always
    ports:
      - "80:80"
    networks:
      - front

networks:
  front:
    driver: bridge


